changelog:
  exclude:
    authors:
      - dependabot
  categories:
    - title: Plugins 🖥️
      labels:
        - plugin
    - title: Interface
      labels:
        - interface
    - title: Other Changes
      labels:
        - '*'
